FROM docker.io/maven:3-jdk-8 as builder
WORKDIR /app
COPY . .
RUN mvn package -P production

FROM docker.io/java:8-alpine
WORKDIR /app
COPY --from=builder /app/target/videomanagement-0.0.1-SNAPSHOT.jar ./service.jar
CMD java -jar service.jar
